import cryptography
from cryptography.fernet import Fernet

key1 = Fernet.generate_key()
#print(key.decode('utf-8'))

fernet = Fernet(key1)
encrypted1 = fernet.encrypt(b"ashdjkasghdjkahsdjkhasjkdhajksd")
encrypted2 = fernet.encrypt(b"ashdjkasghdjkahsdjkhasjkdhajksd")
encrypted3 = fernet.encrypt(b"ashdjkasghdjkahsdjkhasjkdhajksd")
encrypted4 = fernet.encrypt(b"dashdjkasghdjkahsdjkhasjkdhajksdata")
encrypted5 = fernet.encrypt(b"ashdjkasghdjkahsdjkhasjkdhajksd")
encrypted6 = fernet.encrypt(b"ashdjkasghdjkahsdjkhasjkdhajksd")
encrypted7 = fernet.encrypt(b"ashdjkasghdjkahsdjkhasjkdhajksd")
encrypted8 = fernet.encrypt(b"ashdjkasghdjkahsdjkhasjkdhajksd")
print(encrypted1.decode('utf-8'))
print(encrypted2.decode('utf-8'))
print(encrypted3.decode('utf-8'))
print(encrypted4.decode('utf-8'))
print(encrypted5.decode('utf-8'))
print(encrypted6.decode('utf-8'))
print(encrypted7.decode('utf-8'))
print(encrypted8.decode('utf-8'))

decrypted1 = fernet.decrypt(encrypted1)
decrypted2 = fernet.decrypt(encrypted2)
decrypted3 = fernet.decrypt(encrypted3)
decrypted4 = fernet.decrypt(encrypted4)
decrypted5 = fernet.decrypt(encrypted5)
decrypted6 = fernet.decrypt(encrypted6)
decrypted7 = fernet.decrypt(encrypted7)
decrypted8 = fernet.decrypt(encrypted8)
print(decrypted1.decode('utf-8'))
print(decrypted2.decode('utf-8'))
print(decrypted3.decode('utf-8'))
print(decrypted4.decode('utf-8'))
print(decrypted5.decode('utf-8'))
print(decrypted6.decode('utf-8'))
print(decrypted7.decode('utf-8'))
print(decrypted8.decode('utf-8'))